# **LAIBA ARIF**

In [3]:

!pip install Faker

Collecting Faker
  Downloading faker-40.43.0-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.43.0-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 31.6 MB/s eta 0:00:00
Installing collected packages: Faker
Successfully installed Faker-40.43.0

In [4]:

import pandas as pd
import random
from faker import Faker

fake = Faker()
random.seed(42)
Faker.seed(42)

rows = []

universities = [
    "UIT University",
    "NUST",
    "NED University",
    "FAST",
    "Bahria University",
    ""
]

domains = [
    "Data Science",
    "Web Development",
    "UI/UX Design",
    "Cyber Security",
    "AI",
    "web dev",
    "WEB DEV"
]

statuses = [
    "Under Review",
    "Selected",
    "Rejected",
    "selected",
    "REJECTED",
    ""
]

for i in range(100):
    name = fake.name()
    email = fake.email()

    phone = "03" + str(random.randint(0, 9)) + \
            str(random.randint(10000000, 99999999))

    domain = random.choice(domains)
    university = random.choice(universities)
    status = random.choice(statuses)

    date = random.choice([
        "12/05/2026",
        "2026-05-12",
        "15/06/2026"
    ])

    if i % 10 == 0:
        name = "  " + name + "  "

    if i % 12 == 0:
        email = ""

    if i % 15 == 0:
        phone = ""

    if i % 9 == 0:
        university = ""

    rows.append([
        name, email, phone, domain,
        university, date, status
    ])

df = pd.DataFrame(rows, columns=[
    "Applicant Name",
    "Email",
    "Phone",
    "Domain Applied",
    "University",
    "Application Date",
    "Status"
])

df.to_csv("applicants.csv", index=False)

print("CSV created successfully!")
print("Number of rows and columns:", df.shape)

display(df.head(10))

CSV created successfully!
Number of rows and columns: (100, 7)

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Allison Hill,,,web dev,,12/05/2026,Selected
1,Angie Henderson,davisjesse@example.net,03223756669,web dev,,12/05/2026,REJECTED
2,Cristian Santos,lrobinson@example.com,03966629388,Data Science,UIT University,12/05/2026,Under Review
3,Abigail Shaffer,jpeterson@example.org,03377827638,AI,UIT University,12/05/2026,REJECTED
4,Gabrielle Davis,howardmaurice@example.com,03866306997,Web Development,FAST,2026-05-12,REJECTED
5,Monica Herrera,smiller@example.net,03031429110,web dev,FAST,2026-05-12,Rejected
6,Shannon Ray,williamsjeremy@example.com,03238898923,WEB DEV,NED University,12/05/2026,Under Review
7,Dr. Sharon James,xreid@example.org,03622981052,UI/UX Design,NED University,2026-05-12,REJECTED
8,Daniel Adams,lynchgeorge@example.net,03071662963,AI,UIT University,12/05/2026,selected
9,Joel Nelson,gabriellecameron@example.org,03849349722,WEB DEV,,2026-05-12,REJECTED

In [5]:
from google.colab import files
files.download("applicants.csv")

In [7]:
df.shape
df.head()
df.info()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    100 non-null    object
 1   Email             100 non-null    object
 2   Phone             100 non-null    object
 3   Domain Applied    100 non-null    object
 4   University        100 non-null    object
 5   Application Date  100 non-null    object
 6   Status            100 non-null    object
dtypes: object(7)
memory usage: 5.6+ KB

np.int64(0)

The dataset contains 100 rows and 7 columns. All columns currently have the object data type. The initial exact duplicate check returned 0, meaning no completely identical rows were found.

The initial inspection helps identify missing values, inconsistent text formatting, and data type issues before cleaning. Further checks are needed to identify empty strings and variations in domain and status values.

In [12]:
import pandas as pd

df = df.replace(r'^\s*$', pd.NA, regex=True)

print("Missing values before cleaning:")
print(df.isnull().sum())

Missing values before cleaning:
Applicant Name       0
Email                9
Phone                7
Domain Applied       0
University          26
Application Date     0
Status              15
dtype: int64

In [13]:

before_name = len(df)
df = df.dropna(subset=["Applicant Name"])
removed_names = before_name - len(df)

before_email = len(df)
df = df.dropna(subset=["Email"])
removed_emails = before_email - len(df)

df["University"] = df["University"].fillna("Not Specified")

df["Status"] = df["Status"].fillna("Under Review")

print("Rows removed due to missing names:", removed_names)
print("Rows removed due to missing emails:", removed_emails)

print("\nMissing values after Step 4:")
print(df.isnull().sum())

print("\nRemaining dataset shape:", df.shape)

Rows removed due to missing names: 0
Rows removed due to missing emails: 9

Missing values after Step 4:
Applicant Name      0
Email               0
Phone               5
Domain Applied      0
University          0
Application Date    0
Status              0
dtype: int64

Remaining dataset shape: (91, 7)

The dataset initially contained 9 missing Email values, 7 missing Phone values, 26 missing University values, and 15 missing Status values.

Rows with missing Applicant Name were removed because the applicant could not be reliably identified. Rows with missing Email were also removed because email is important for follow-up.

Missing University values were filled with "Not Specified" because this information is not essential for identifying an application. Missing Status values were filled with "Under Review" because these applications may not have been processed yet.

Phone values were left unchanged at this stage for further consideration.

The number of rows removed and the remaining missing values were checked after applying these changes.

In [14]:
exact_duplicates = df.duplicated().sum()

print("Exact duplicate rows:", exact_duplicates)

df = df.drop_duplicates()

print("Dataset shape after removing exact duplicates:", df.shape)

Exact duplicate rows: 0
Dataset shape after removing exact duplicates: (91, 7)

In [15]:
duplicate_emails = df["Email"].duplicated().sum()

print("Duplicate email entries:", duplicate_emails)

display(
    df[df["Email"].duplicated(keep=False)]
    .sort_values("Email")
)

Duplicate email entries: 0

Empty DataFrame
Columns: [Applicant Name, Email, Phone, Domain Applied, University, Application Date, Status]
Index: []

I checked the dataset for exact duplicate rows using `df.duplicated().sum()`. The result was 0, so no completely identical rows were found.

I also checked for duplicate email addresses because email can help identify repeated applications from the same applicant. The result was 0 duplicate email entries.

No rows were removed during this step because no exact duplicates or duplicate email addresses were detected. The dataset remains at 91 rows and 7 columns.

Email was chosen as a duplicate-checking field because names may be shared by different applicants, while email addresses are generally more useful for identifying repeated applications.

In [16]:
text_columns = [
    "Applicant Name",
    "Email",
    "Phone",
    "Domain Applied",
    "University",
    "Status"
]

for col in text_columns:
    df[col] = df[col].str.strip()

df["Applicant Name"] = df["Applicant Name"].str.title()

df["Email"] = df["Email"].str.lower()

df["University"] = df["University"].str.title()

display(df.head())

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
1,Angie Henderson,davisjesse@example.net,03223756669,web dev,Not Specified,12/05/2026,REJECTED
2,Cristian Santos,lrobinson@example.com,03966629388,Data Science,Uit University,12/05/2026,Under Review
3,Abigail Shaffer,jpeterson@example.org,03377827638,AI,Uit University,12/05/2026,REJECTED
4,Gabrielle Davis,howardmaurice@example.com,03866306997,Web Development,Fast,2026-05-12,REJECTED
5,Monica Herrera,smiller@example.net,03031429110,web dev,Fast,2026-05-12,Rejected

In [17]:
print("Domains before standardization:")
print(df["Domain Applied"].unique())

domain_mapping = {
    "data science": "Data Science",
    "web dev": "Web Development",
    "web development": "Web Development",
    "ui/ux design": "UI/UX Design",
    "cyber security": "Cyber Security",
    "ai": "AI"
}

df["Domain Applied"] = df["Domain Applied"].str.lower().str.strip()

df["Domain Applied"] = df["Domain Applied"].map(domain_mapping)

print("\nDomains after standardization:")
print(df["Domain Applied"].unique())

print("\nMissing domain values after mapping:")
print(df["Domain Applied"].isnull().sum())

Domains before standardization:
['web dev' 'Data Science' 'AI' 'Web Development' 'WEB DEV' 'UI/UX Design'
 'Cyber Security']

Domains after standardization:
['Web Development' 'Data Science' 'AI' 'UI/UX Design' 'Cyber Security']

Missing domain values after mapping:
0

In [18]:
df["Status"] = df["Status"].str.strip().str.title()
print("Unique status values:")
print(df["Status"].unique())

Unique status values:
['Rejected' 'Under Review' 'Selected']

I removed leading and trailing whitespace from text columns using `str.strip()`. I standardized applicant names and university text formatting and converted email addresses to lowercase.

I used a mapping dictionary to convert inconsistent domain labels, such as "web dev" and "WEB DEV", into the standard label "Web Development".

I also standardized application statuses using title case so that values such as "selected" and "SELECTED" are represented consistently.

Finally, I checked the unique domain and status values to verify the results and identify any unmapped domain variations.

In [19]:
print("Date type before conversion:")
print(df["Application Date"].dtype)

df["Application Date"] = pd.to_datetime(
    df["Application Date"],
    errors="coerce",
    dayfirst=True
)
print("\nDate type after conversion:")
print(df["Application Date"].dtype)
print("\nMissing dates after conversion:")
print(df["Application Date"].isnull().sum())
display(df[["Application Date"]].head())

Date type before conversion:
object

Date type after conversion:
datetime64[ns]

Missing dates after conversion:
30

  Application Date
1       2026-05-12
2       2026-05-12
3       2026-05-12
4              NaT
5              NaT

In [20]:
df["Phone"] = (
    df["Phone"]
    .str.replace("-", "", regex=False)
    .str.replace(" ", "", regex=False)
)

print("Phone numbers after cleaning:")
display(df[["Phone"]].head(10))

print("\nMissing phone values:")
print(df["Phone"].isnull().sum())

Phone numbers after cleaning:

          Phone
1   03223756669
2   03966629388
3   03377827638
4   03866306997
5   03031429110
6   03238898923
7   03622981052
8   03071662963
9   03849349722
10  03935808537

Missing phone values:
5

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 91 entries, 1 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    91 non-null     object
 1   Email             91 non-null     object
 2   Phone             86 non-null     object
 3   Domain Applied    91 non-null     object
 4   University        91 non-null     object
 5   Application Date  61 non-null     datetime64[ns]
 6   Status            91 non-null     object
dtypes: datetime64[ns](1), object(6)
memory usage: 5.7+ KB

I converted the Application Date column from text to a proper datetime format using `pd.to_datetime()` with `errors='coerce'` and `dayfirst=True`. Unreadable dates are converted to `NaT` so they can be identified and handled.

I removed dashes and spaces from phone numbers using `str.replace()`. Phone numbers remain stored as text because converting them to numbers could remove leading zeros.

I used `df.info()` to verify the data types after these changes.

In [22]:
print("DATA QUALITY SUMMARY")
print("--------------------")

print("Total rows:", len(df))
print("Total columns:", len(df.columns))

print("\nMissing values in each column:")
print(df.isnull().sum())

print("\nTotal missing values:", df.isnull().sum().sum())
print("Exact duplicate rows:", df.duplicated().sum())
print("Duplicate emails:", df["Email"].duplicated().sum())

print("\nUnique application domains:")
print(df["Domain Applied"].unique())

print("\nApplication Date data type:")
print(df["Application Date"].dtype)

print("\nFinal dataset information:")
df.info()

DATA QUALITY SUMMARY
--------------------
Total rows: 91
Total columns: 7

Missing values in each column:
Applicant Name       0
Email                0
Phone                5
Domain Applied       0
University           0
Application Date    30
Status               0
dtype: int64

Total missing values: 35
Exact duplicate rows: 0
Duplicate emails: 0

Unique application domains:
['Web Development' 'Data Science' 'AI' 'UI/UX Design' 'Cyber Security']

Application Date data type:
datetime64[ns]

Final dataset information:
<class 'pandas.core.frame.DataFrame'>
Index: 91 entries, 1 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    91 non-null     object
 1   Email             91 non-null     object
 2   Phone             86 non-null     object
 3   Domain Applied    91 non-null     object
 4   University        91 non-null     object
 5   Application Date  61 non-null     datetime64[ns]
 6   Status            91 non-null     object
dtypes: datetime64[ns](1), object(6)
memory usage: 5.7+ KB

## Data Quality Summary

The applicant dataset was cleaned by handling missing values, removing duplicate records, standardizing text values, and converting application dates into datetime format.

- Missing names and emails were handled by removing rows with missing values.
- Missing university names were replaced with "Not Specified".
- Missing statuses were replaced with "Under Review".
- Domain names and application statuses were standardized.
- Phone numbers were cleaned by removing hyphens and spaces.
- Application dates were converted into datetime format.

The final dataset was checked for missing values, duplicate records, and consistent domain categories.

In [23]:
df.to_csv("applicants_cleaned.csv", index=False)

print("Cleaned CSV file saved successfully!")

Cleaned CSV file saved successfully!